// This file is auto-generated by scripts/generate-tokens.ts
// Do not edit manually. Update figma/exported-styles.json and run `pnpm generate`

// =============================================================================
// Color Tokens
// =============================================================================

// Base
/** Base - shade White */
export const BaseWhite = "#ffffff" as const;
/** Base - shade Black */
export const BaseBlack = "#0e0e3f" as const;

// Gray (light mode)
/** Gray (light mode) - shade 25 */
export const Graylightmode25 = "#fdfdfd" as const;
/** Gray (light mode) - shade 50 */
export const Graylightmode50 = "#fafafa" as const;
/** Gray (light mode) - shade 100 */
export const Graylightmode100 = "#f5f5f5" as const;
/** Gray (light mode) - shade 200 */
export const Graylightmode200 = "#e9eaeb" as const;
/** Gray (light mode) - shade 300 */
export const Graylightmode300 = "#d5d7da" as const;
/** Gray (light mode) - shade 400 */
export const Graylightmode400 = "#a4a7ae" as const;
/** Gray (light mode) - shade 500 */
export const Graylightmode500 = "#717680" as const;
/** Gray (light mode) - shade 600 */
export const Graylightmode600 = "#535862" as const;
/** Gray (light mode) - shade 700 */
export const Graylightmode700 = "#414651" as const;
/** Gray (light mode) - shade 800 */
export const Graylightmode800 = "#252b37" as const;
/** Gray (light mode) - shade 900 */
export const Graylightmode900 = "#181d27" as const;
/** Gray (light mode) - shade 950 */
export const Graylightmode950 = "#0e0e3f" as const;

// Gray (dark mode)
/** Gray (dark mode) - shade 25 */
export const Graydarkmode25 = "#fafafa" as const;
/** Gray (dark mode) - shade 50 */
export const Graydarkmode50 = "#f7f7f7" as const;
/** Gray (dark mode) - shade 100 */
export const Graydarkmode100 = "#f0f0f1" as const;
/** Gray (dark mode) - shade 200 */
export const Graydarkmode200 = "#ececed" as const;
/** Gray (dark mode) - shade 300 */
export const Graydarkmode300 = "#cecfd2" as const;
/** Gray (dark mode) - shade 400 */
export const Graydarkmode400 = "#94979c" as const;
/** Gray (dark mode) - shade 500 */
export const Graydarkmode500 = "#85888e" as const;
/** Gray (dark mode) - shade 600 */
export const Graydarkmode600 = "#61656c" as const;
/** Gray (dark mode) - shade 700 */
export const Graydarkmode700 = "#373a41" as const;
/** Gray (dark mode) - shade 800 */
export const Graydarkmode800 = "#22262f" as const;
/** Gray (dark mode) - shade 900 */
export const Graydarkmode900 = "#13161b" as const;
/** Gray (dark mode) - shade 950 */
export const Graydarkmode950 = "#0c0e12" as const;

// Brand
/** Brand - shade 25 */
export const Brand25 = "#e8f1f9" as const;
/** Brand - shade 50 */
export const Brand50 = "#d0e3f4" as const;
/** Brand - shade 100 */
export const Brand100 = "#b9d5ee" as const;
/** Brand - shade 200 */
export const Brand200 = "#a1c7e9" as const;
/** Brand - shade 300 */
export const Brand300 = "#73acdd" as const;
/** Brand - shade 400 */
export const Brand400 = "#4490d2" as const;
/** Brand - shade 500 */
export const Brand500 = "#1574c7" as const;
/** Brand - shade 600 */
export const Brand600 = "#115d9f" as const;
/** Brand - shade 700 */
export const Brand700 = "#0d4677" as const;
/** Brand - shade 800 */
export const Brand800 = "#082e50" as const;
/** Brand - shade 900 */
export const Brand900 = "#041728" as const;
/** Brand - shade 950 */
export const Brand950 = "#020c14" as const;

// Error
/** Error - shade 25 */
export const Error25 = "#fffbfa" as const;
/** Error - shade 50 */
export const Error50 = "#fef3f2" as const;
/** Error - shade 100 */
export const Error100 = "#fee4e2" as const;
/** Error - shade 200 */
export const Error200 = "#fecdca" as const;
/** Error - shade 300 */
export const Error300 = "#fda29b" as const;
/** Error - shade 400 */
export const Error400 = "#f97066" as const;
/** Error - shade 500 */
export const Error500 = "#f04438" as const;
/** Error - shade 600 */
export const Error600 = "#d92d20" as const;
/** Error - shade 700 */
export const Error700 = "#b42318" as const;
/** Error - shade 800 */
export const Error800 = "#912018" as const;
/** Error - shade 900 */
export const Error900 = "#7a271a" as const;
/** Error - shade 950 */
export const Error950 = "#55160c" as const;

// Warning
/** Warning - shade 25 */
export const Warning25 = "#fffcf5" as const;
/** Warning - shade 50 */
export const Warning50 = "#fffaeb" as const;
/** Warning - shade 100 */
export const Warning100 = "#fef0c7" as const;
/** Warning - shade 200 */
export const Warning200 = "#fedf89" as const;
/** Warning - shade 300 */
export const Warning300 = "#fec84b" as const;
/** Warning - shade 400 */
export const Warning400 = "#fdb022" as const;
/** Warning - shade 500 */
export const Warning500 = "#f79009" as const;
/** Warning - shade 600 */
export const Warning600 = "#dc6803" as const;
/** Warning - shade 700 */
export const Warning700 = "#b54708" as const;
/** Warning - shade 800 */
export const Warning800 = "#93370d" as const;
/** Warning - shade 900 */
export const Warning900 = "#7a2e0e" as const;
/** Warning - shade 950 */
export const Warning950 = "#4e1d09" as const;

// Success
/** Success - shade 25 */
export const Success25 = "#f6fef9" as const;
/** Success - shade 50 */
export const Success50 = "#ecfdf3" as const;
/** Success - shade 100 */
export const Success100 = "#dcfae6" as const;
/** Success - shade 200 */
export const Success200 = "#abefc6" as const;
/** Success - shade 300 */
export const Success300 = "#75e0a7" as const;
/** Success - shade 400 */
export const Success400 = "#47cd89" as const;
/** Success - shade 500 */
export const Success500 = "#17b26a" as const;
/** Success - shade 600 */
export const Success600 = "#079455" as const;
/** Success - shade 700 */
export const Success700 = "#067647" as const;
/** Success - shade 800 */
export const Success800 = "#085d3a" as const;
/** Success - shade 900 */
export const Success900 = "#074d31" as const;
/** Success - shade 950 */
export const Success950 = "#053321" as const;

// Gray blue
/** Gray blue - shade 25 */
export const Grayblue25 = "#fcfcfd" as const;
/** Gray blue - shade 50 */
export const Grayblue50 = "#f8f9fc" as const;
/** Gray blue - shade 100 */
export const Grayblue100 = "#eaecf5" as const;
/** Gray blue - shade 200 */
export const Grayblue200 = "#d5d9eb" as const;
/** Gray blue - shade 300 */
export const Grayblue300 = "#b3b8db" as const;
/** Gray blue - shade 400 */
export const Grayblue400 = "#717bbc" as const;
/** Gray blue - shade 500 */
export const Grayblue500 = "#4e5ba6" as const;
/** Gray blue - shade 600 */
export const Grayblue600 = "#3e4784" as const;
/** Gray blue - shade 700 */
export const Grayblue700 = "#363f72" as const;
/** Gray blue - shade 800 */
export const Grayblue800 = "#293056" as const;
/** Gray blue - shade 900 */
export const Grayblue900 = "#101323" as const;
/** Gray blue - shade 950 */
export const Grayblue950 = "#0d0f1c" as const;

// Gray cool
/** Gray cool - shade 25 */
export const Graycool25 = "#fcfcfd" as const;
/** Gray cool - shade 50 */
export const Graycool50 = "#f9f9fb" as const;
/** Gray cool - shade 100 */
export const Graycool100 = "#eff1f5" as const;
/** Gray cool - shade 200 */
export const Graycool200 = "#dcdfea" as const;
/** Gray cool - shade 300 */
export const Graycool300 = "#b9c0d4" as const;
/** Gray cool - shade 400 */
export const Graycool400 = "#7d89b0" as const;
/** Gray cool - shade 500 */
export const Graycool500 = "#5d6b98" as const;
/** Gray cool - shade 600 */
export const Graycool600 = "#4a5578" as const;
/** Gray cool - shade 700 */
export const Graycool700 = "#404968" as const;
/** Gray cool - shade 800 */
export const Graycool800 = "#30374f" as const;
/** Gray cool - shade 900 */
export const Graycool900 = "#111322" as const;
/** Gray cool - shade 950 */
export const Graycool950 = "#0e101b" as const;

// Gray modern
/** Gray modern - shade 25 */
export const Graymodern25 = "#fcfcfd" as const;
/** Gray modern - shade 50 */
export const Graymodern50 = "#f8fafc" as const;
/** Gray modern - shade 100 */
export const Graymodern100 = "#eef2f6" as const;
/** Gray modern - shade 200 */
export const Graymodern200 = "#e3e8ef" as const;
/** Gray modern - shade 300 */
export const Graymodern300 = "#cdd5df" as const;
/** Gray modern - shade 400 */
export const Graymodern400 = "#9aa4b2" as const;
/** Gray modern - shade 500 */
export const Graymodern500 = "#697586" as const;
/** Gray modern - shade 600 */
export const Graymodern600 = "#4b5565" as const;
/** Gray modern - shade 700 */
export const Graymodern700 = "#364152" as const;
/** Gray modern - shade 800 */
export const Graymodern800 = "#202939" as const;
/** Gray modern - shade 900 */
export const Graymodern900 = "#121926" as const;
/** Gray modern - shade 950 */
export const Graymodern950 = "#0d121c" as const;

// Gray neutral
/** Gray neutral - shade 25 */
export const Grayneutral25 = "#fcfcfd" as const;
/** Gray neutral - shade 50 */
export const Grayneutral50 = "#f9fafb" as const;
/** Gray neutral - shade 100 */
export const Grayneutral100 = "#f3f4f6" as const;
/** Gray neutral - shade 200 */
export const Grayneutral200 = "#e5e7eb" as const;
/** Gray neutral - shade 300 */
export const Grayneutral300 = "#d2d6db" as const;
/** Gray neutral - shade 400 */
export const Grayneutral400 = "#9da4ae" as const;
/** Gray neutral - shade 500 */
export const Grayneutral500 = "#6c737f" as const;
/** Gray neutral - shade 600 */
export const Grayneutral600 = "#4d5761" as const;
/** Gray neutral - shade 700 */
export const Grayneutral700 = "#384250" as const;
/** Gray neutral - shade 800 */
export const Grayneutral800 = "#1f2a37" as const;
/** Gray neutral - shade 900 */
export const Grayneutral900 = "#111927" as const;
/** Gray neutral - shade 950 */
export const Grayneutral950 = "#0d121c" as const;

// Gray iron
/** Gray iron - shade 25 */
export const Grayiron25 = "#fcfcfc" as const;
/** Gray iron - shade 50 */
export const Grayiron50 = "#fafafa" as const;
/** Gray iron - shade 100 */
export const Grayiron100 = "#f4f4f5" as const;
/** Gray iron - shade 200 */
export const Grayiron200 = "#e4e4e7" as const;
/** Gray iron - shade 300 */
export const Grayiron300 = "#d1d1d6" as const;
/** Gray iron - shade 400 */
export const Grayiron400 = "#a0a0ab" as const;
/** Gray iron - shade 500 */
export const Grayiron500 = "#70707b" as const;
/** Gray iron - shade 600 */
export const Grayiron600 = "#51525c" as const;
/** Gray iron - shade 700 */
export const Grayiron700 = "#3f3f46" as const;
/** Gray iron - shade 800 */
export const Grayiron800 = "#26272b" as const;
/** Gray iron - shade 900 */
export const Grayiron900 = "#1a1a1e" as const;
/** Gray iron - shade 950 */
export const Grayiron950 = "#131316" as const;

// Gray true
/** Gray true - shade 25 */
export const Graytrue25 = "#fcfcfc" as const;
/** Gray true - shade 50 */
export const Graytrue50 = "#f7f7f7" as const;
/** Gray true - shade 100 */
export const Graytrue100 = "#f5f5f5" as const;
/** Gray true - shade 200 */
export const Graytrue200 = "#e5e5e5" as const;
/** Gray true - shade 300 */
export const Graytrue300 = "#d6d6d6" as const;
/** Gray true - shade 400 */
export const Graytrue400 = "#a3a3a3" as const;
/** Gray true - shade 500 */
export const Graytrue500 = "#737373" as const;
/** Gray true - shade 600 */
export const Graytrue600 = "#525252" as const;
/** Gray true - shade 700 */
export const Graytrue700 = "#424242" as const;
/** Gray true - shade 800 */
export const Graytrue800 = "#292929" as const;
/** Gray true - shade 900 */
export const Graytrue900 = "#141414" as const;
/** Gray true - shade 950 */
export const Graytrue950 = "#0f0f0f" as const;

// Gray warm
/** Gray warm - shade 25 */
export const Graywarm25 = "#fdfdfc" as const;
/** Gray warm - shade 50 */
export const Graywarm50 = "#fafaf9" as const;
/** Gray warm - shade 100 */
export const Graywarm100 = "#f5f5f4" as const;
/** Gray warm - shade 200 */
export const Graywarm200 = "#e7e5e4" as const;
/** Gray warm - shade 300 */
export const Graywarm300 = "#d7d3d0" as const;
/** Gray warm - shade 400 */
export const Graywarm400 = "#a9a29d" as const;
/** Gray warm - shade 500 */
export const Graywarm500 = "#79716b" as const;
/** Gray warm - shade 600 */
export const Graywarm600 = "#57534e" as const;
/** Gray warm - shade 700 */
export const Graywarm700 = "#44403c" as const;
/** Gray warm - shade 800 */
export const Graywarm800 = "#292524" as const;
/** Gray warm - shade 900 */
export const Graywarm900 = "#1c1917" as const;
/** Gray warm - shade 950 */
export const Graywarm950 = "#171412" as const;

// Moss
/** Moss - shade 25 */
export const Moss25 = "#fafdf7" as const;
/** Moss - shade 50 */
export const Moss50 = "#f5fbee" as const;
/** Moss - shade 100 */
export const Moss100 = "#e6f4d7" as const;
/** Moss - shade 200 */
export const Moss200 = "#ceeab0" as const;
/** Moss - shade 300 */
export const Moss300 = "#acdc79" as const;
/** Moss - shade 400 */
export const Moss400 = "#86cb3c" as const;
/** Moss - shade 500 */
export const Moss500 = "#669f2a" as const;
/** Moss - shade 600 */
export const Moss600 = "#4f7a21" as const;
/** Moss - shade 700 */
export const Moss700 = "#3f621a" as const;
/** Moss - shade 800 */
export const Moss800 = "#335015" as const;
/** Moss - shade 900 */
export const Moss900 = "#2b4212" as const;
/** Moss - shade 950 */
export const Moss950 = "#1a280b" as const;

// Green light
/** Green light - shade 25 */
export const Greenlight25 = "#fafef5" as const;
/** Green light - shade 50 */
export const Greenlight50 = "#f3fee7" as const;
/** Green light - shade 100 */
export const Greenlight100 = "#e3fbcc" as const;
/** Green light - shade 200 */
export const Greenlight200 = "#d0f8ab" as const;
/** Green light - shade 300 */
export const Greenlight300 = "#a6ef67" as const;
/** Green light - shade 400 */
export const Greenlight400 = "#85e13a" as const;
/** Green light - shade 500 */
export const Greenlight500 = "#66c61c" as const;
/** Green light - shade 600 */
export const Greenlight600 = "#4ca30d" as const;
/** Green light - shade 700 */
export const Greenlight700 = "#3b7c0f" as const;
/** Green light - shade 800 */
export const Greenlight800 = "#326212" as const;
/** Green light - shade 900 */
export const Greenlight900 = "#2b5314" as const;
/** Green light - shade 950 */
export const Greenlight950 = "#15290a" as const;

// Green
/** Green - shade 25 */
export const Green25 = "#f6fef9" as const;
/** Green - shade 50 */
export const Green50 = "#edfcf2" as const;
/** Green - shade 100 */
export const Green100 = "#d3f8df" as const;
/** Green - shade 200 */
export const Green200 = "#aaf0c4" as const;
/** Green - shade 300 */
export const Green300 = "#73e2a3" as const;
/** Green - shade 400 */
export const Green400 = "#3ccb7f" as const;
/** Green - shade 500 */
export const Green500 = "#16b364" as const;
/** Green - shade 600 */
export const Green600 = "#099250" as const;
/** Green - shade 700 */
export const Green700 = "#087443" as const;
/** Green - shade 800 */
export const Green800 = "#095c37" as const;
/** Green - shade 900 */
export const Green900 = "#084c2e" as const;
/** Green - shade 950 */
export const Green950 = "#052e1c" as const;

// Teal
/** Teal - shade 25 */
export const Teal25 = "#f6fefc" as const;
/** Teal - shade 50 */
export const Teal50 = "#f0fdf9" as const;
/** Teal - shade 100 */
export const Teal100 = "#ccfbef" as const;
/** Teal - shade 200 */
export const Teal200 = "#99f6e0" as const;
/** Teal - shade 300 */
export const Teal300 = "#5fe9d0" as const;
/** Teal - shade 400 */
export const Teal400 = "#2ed3b7" as const;
/** Teal - shade 500 */
export const Teal500 = "#15b79e" as const;
/** Teal - shade 600 */
export const Teal600 = "#0e9384" as const;
/** Teal - shade 700 */
export const Teal700 = "#107569" as const;
/** Teal - shade 800 */
export const Teal800 = "#125d56" as const;
/** Teal - shade 900 */
export const Teal900 = "#134e48" as const;
/** Teal - shade 950 */
export const Teal950 = "#0a2926" as const;

// Cyan
/** Cyan - shade 25 */
export const Cyan25 = "#f5feff" as const;
/** Cyan - shade 50 */
export const Cyan50 = "#ecfdff" as const;
/** Cyan - shade 100 */
export const Cyan100 = "#cff9fe" as const;
/** Cyan - shade 200 */
export const Cyan200 = "#a5f0fc" as const;
/** Cyan - shade 300 */
export const Cyan300 = "#67e3f9" as const;
/** Cyan - shade 400 */
export const Cyan400 = "#22ccee" as const;
/** Cyan - shade 500 */
export const Cyan500 = "#06aed4" as const;
/** Cyan - shade 600 */
export const Cyan600 = "#088ab2" as const;
/** Cyan - shade 700 */
export const Cyan700 = "#0e7090" as const;
/** Cyan - shade 800 */
export const Cyan800 = "#155b75" as const;
/** Cyan - shade 900 */
export const Cyan900 = "#164c63" as const;
/** Cyan - shade 950 */
export const Cyan950 = "#0d2d3a" as const;

// Blue light
/** Blue light - shade 25 */
export const Bluelight25 = "#f6feff" as const;
/** Blue light - shade 50 */
export const Bluelight50 = "#f0f9ff" as const;
/** Blue light - shade 100 */
export const Bluelight100 = "#e0f2fe" as const;
/** Blue light - shade 200 */
export const Bluelight200 = "#b9e6fe" as const;
/** Blue light - shade 300 */
export const Bluelight300 = "#7cd4fd" as const;
/** Blue light - shade 400 */
export const Bluelight400 = "#36bffa" as const;
/** Blue light - shade 500 */
export const Bluelight500 = "#0ba5ec" as const;
/** Blue light - shade 600 */
export const Bluelight600 = "#0086c9" as const;
/** Blue light - shade 700 */
export const Bluelight700 = "#026aa2" as const;
/** Blue light - shade 800 */
export const Bluelight800 = "#065986" as const;
/** Blue light - shade 900 */
export const Bluelight900 = "#0b4a6f" as const;
/** Blue light - shade 950 */
export const Bluelight950 = "#062c41" as const;

// Blue
/** Blue - shade 25 */
export const Blue25 = "#e6f2ff" as const;
/** Blue - shade 50 */
export const Blue50 = "#cce5fe" as const;
/** Blue - shade 100 */
export const Blue100 = "#b3d7fe" as const;
/** Blue - shade 200 */
export const Blue200 = "#9acafe" as const;
/** Blue - shade 300 */
export const Blue300 = "#67b0fd" as const;
/** Blue - shade 400 */
export const Blue400 = "#3595fd" as const;
/** Blue - shade 500 */
export const Blue500 = "#027bfc" as const;
/** Blue - shade 600 */
export const Blue600 = "#0262ca" as const;
/** Blue - shade 700 */
export const Blue700 = "#014a97" as const;
/** Blue - shade 800 */
export const Blue800 = "#013165" as const;
/** Blue - shade 900 */
export const Blue900 = "#01254c" as const;
/** Blue - shade 950 */
export const Blue950 = "#001932" as const;

// Blue dark
/** Blue dark - shade 25 */
export const Bluedark25 = "#f5f8ff" as const;
/** Blue dark - shade 50 */
export const Bluedark50 = "#eff4ff" as const;
/** Blue dark - shade 100 */
export const Bluedark100 = "#d1e0ff" as const;
/** Blue dark - shade 200 */
export const Bluedark200 = "#b2ccff" as const;
/** Blue dark - shade 300 */
export const Bluedark300 = "#84adff" as const;
/** Blue dark - shade 400 */
export const Bluedark400 = "#528bff" as const;
/** Blue dark - shade 500 */
export const Bluedark500 = "#2970ff" as const;
/** Blue dark - shade 600 */
export const Bluedark600 = "#155eef" as const;
/** Blue dark - shade 700 */
export const Bluedark700 = "#004eeb" as const;
/** Blue dark - shade 800 */
export const Bluedark800 = "#0040c1" as const;
/** Blue dark - shade 900 */
export const Bluedark900 = "#00359e" as const;
/** Blue dark - shade 950 */
export const Bluedark950 = "#002266" as const;

// Indigo
/** Indigo - shade 25 */
export const Indigo25 = "#f5f8ff" as const;
/** Indigo - shade 50 */
export const Indigo50 = "#eef4ff" as const;
/** Indigo - shade 100 */
export const Indigo100 = "#e0eaff" as const;
/** Indigo - shade 200 */
export const Indigo200 = "#c7d7fe" as const;
/** Indigo - shade 300 */
export const Indigo300 = "#a4bcfd" as const;
/** Indigo - shade 400 */
export const Indigo400 = "#8098f9" as const;
/** Indigo - shade 500 */
export const Indigo500 = "#6172f3" as const;
/** Indigo - shade 600 */
export const Indigo600 = "#444ce7" as const;
/** Indigo - shade 700 */
export const Indigo700 = "#3538cd" as const;
/** Indigo - shade 800 */
export const Indigo800 = "#2d31a6" as const;
/** Indigo - shade 900 */
export const Indigo900 = "#2d3282" as const;
/** Indigo - shade 950 */
export const Indigo950 = "#1f235b" as const;

// Violet
/** Violet - shade 25 */
export const Violet25 = "#fbfaff" as const;
/** Violet - shade 50 */
export const Violet50 = "#f5f3ff" as const;
/** Violet - shade 100 */
export const Violet100 = "#ece9fe" as const;
/** Violet - shade 200 */
export const Violet200 = "#ddd6fe" as const;
/** Violet - shade 300 */
export const Violet300 = "#c3b5fd" as const;
/** Violet - shade 400 */
export const Violet400 = "#a48afb" as const;
/** Violet - shade 500 */
export const Violet500 = "#875bf7" as const;
/** Violet - shade 600 */
export const Violet600 = "#7839ee" as const;
/** Violet - shade 700 */
export const Violet700 = "#6927da" as const;
/** Violet - shade 800 */
export const Violet800 = "#5720b7" as const;
/** Violet - shade 900 */
export const Violet900 = "#491c96" as const;
/** Violet - shade 950 */
export const Violet950 = "#2e125e" as const;

// Purple
/** Purple - shade 25 */
export const Purple25 = "#fafaff" as const;
/** Purple - shade 50 */
export const Purple50 = "#f4f3ff" as const;
/** Purple - shade 100 */
export const Purple100 = "#ebe9fe" as const;
/** Purple - shade 200 */
export const Purple200 = "#d9d6fe" as const;
/** Purple - shade 300 */
export const Purple300 = "#bdb4fe" as const;
/** Purple - shade 400 */
export const Purple400 = "#9b8afb" as const;
/** Purple - shade 500 */
export const Purple500 = "#7a5af8" as const;
/** Purple - shade 600 */
export const Purple600 = "#6938ef" as const;
/** Purple - shade 700 */
export const Purple700 = "#5925dc" as const;
/** Purple - shade 800 */
export const Purple800 = "#4a1fb8" as const;
/** Purple - shade 900 */
export const Purple900 = "#3e1c96" as const;
/** Purple - shade 950 */
export const Purple950 = "#27115f" as const;

// Fuchsia
/** Fuchsia - shade 25 */
export const Fuchsia25 = "#fefaff" as const;
/** Fuchsia - shade 50 */
export const Fuchsia50 = "#fdf4ff" as const;
/** Fuchsia - shade 100 */
export const Fuchsia100 = "#fbe8ff" as const;
/** Fuchsia - shade 200 */
export const Fuchsia200 = "#f6d0fe" as const;
/** Fuchsia - shade 300 */
export const Fuchsia300 = "#eeaafd" as const;
/** Fuchsia - shade 400 */
export const Fuchsia400 = "#e478fa" as const;
/** Fuchsia - shade 500 */
export const Fuchsia500 = "#d444f1" as const;
/** Fuchsia - shade 600 */
export const Fuchsia600 = "#ba24d5" as const;
/** Fuchsia - shade 700 */
export const Fuchsia700 = "#9f1ab1" as const;
/** Fuchsia - shade 800 */
export const Fuchsia800 = "#821890" as const;
/** Fuchsia - shade 900 */
export const Fuchsia900 = "#6f1877" as const;
/** Fuchsia - shade 950 */
export const Fuchsia950 = "#47104c" as const;

// Pink
/** Pink - shade 25 */
export const Pink25 = "#fef6fb" as const;
/** Pink - shade 50 */
export const Pink50 = "#fdf2fa" as const;
/** Pink - shade 100 */
export const Pink100 = "#fce7f6" as const;
/** Pink - shade 200 */
export const Pink200 = "#fcceee" as const;
/** Pink - shade 300 */
export const Pink300 = "#faa7e0" as const;
/** Pink - shade 400 */
export const Pink400 = "#f670c7" as const;
/** Pink - shade 500 */
export const Pink500 = "#ee46bc" as const;
/** Pink - shade 600 */
export const Pink600 = "#dd2590" as const;
/** Pink - shade 700 */
export const Pink700 = "#c11574" as const;
/** Pink - shade 800 */
export const Pink800 = "#9e165f" as const;
/** Pink - shade 900 */
export const Pink900 = "#851651" as const;
/** Pink - shade 950 */
export const Pink950 = "#4e0d30" as const;

// Rose
/** Rose - shade 25 */
export const Rose25 = "#fff5f6" as const;
/** Rose - shade 50 */
export const Rose50 = "#fff1f3" as const;
/** Rose - shade 100 */
export const Rose100 = "#ffe4e8" as const;
/** Rose - shade 200 */
export const Rose200 = "#fecdd6" as const;
/** Rose - shade 300 */
export const Rose300 = "#fea3b4" as const;
/** Rose - shade 400 */
export const Rose400 = "#fd6f8e" as const;
/** Rose - shade 500 */
export const Rose500 = "#f63d68" as const;
/** Rose - shade 600 */
export const Rose600 = "#e31b54" as const;
/** Rose - shade 700 */
export const Rose700 = "#c01048" as const;
/** Rose - shade 800 */
export const Rose800 = "#a11043" as const;
/** Rose - shade 900 */
export const Rose900 = "#89123e" as const;
/** Rose - shade 950 */
export const Rose950 = "#510b24" as const;

// Orange dark
/** Orange dark - shade 25 */
export const Orangedark25 = "#fff9f5" as const;
/** Orange dark - shade 50 */
export const Orangedark50 = "#fff4ed" as const;
/** Orange dark - shade 100 */
export const Orangedark100 = "#ffe6d5" as const;
/** Orange dark - shade 200 */
export const Orangedark200 = "#ffd6ae" as const;
/** Orange dark - shade 300 */
export const Orangedark300 = "#ff9c66" as const;
/** Orange dark - shade 400 */
export const Orangedark400 = "#ff692e" as const;
/** Orange dark - shade 500 */
export const Orangedark500 = "#ff4405" as const;
/** Orange dark - shade 600 */
export const Orangedark600 = "#e62e05" as const;
/** Orange dark - shade 700 */
export const Orangedark700 = "#bc1b06" as const;
/** Orange dark - shade 800 */
export const Orangedark800 = "#97180c" as const;
/** Orange dark - shade 900 */
export const Orangedark900 = "#771a0d" as const;
/** Orange dark - shade 950 */
export const Orangedark950 = "#57130a" as const;

// Orange
/** Orange - shade 25 */
export const Orange25 = "#fefaf5" as const;
/** Orange - shade 50 */
export const Orange50 = "#fef6ee" as const;
/** Orange - shade 100 */
export const Orange100 = "#fdead7" as const;
/** Orange - shade 200 */
export const Orange200 = "#f9dbaf" as const;
/** Orange - shade 300 */
export const Orange300 = "#f7b27a" as const;
/** Orange - shade 400 */
export const Orange400 = "#f38744" as const;
/** Orange - shade 500 */
export const Orange500 = "#ef6820" as const;
/** Orange - shade 600 */
export const Orange600 = "#e04f16" as const;
/** Orange - shade 700 */
export const Orange700 = "#b93815" as const;
/** Orange - shade 800 */
export const Orange800 = "#932f19" as const;
/** Orange - shade 900 */
export const Orange900 = "#772917" as const;
/** Orange - shade 950 */
export const Orange950 = "#511c10" as const;

// Yellow
/** Yellow - shade 25 */
export const Yellow25 = "#fefdf0" as const;
/** Yellow - shade 50 */
export const Yellow50 = "#fefbe8" as const;
/** Yellow - shade 100 */
export const Yellow100 = "#fef7c3" as const;
/** Yellow - shade 200 */
export const Yellow200 = "#feee95" as const;
/** Yellow - shade 300 */
export const Yellow300 = "#fde272" as const;
/** Yellow - shade 400 */
export const Yellow400 = "#fac515" as const;
/** Yellow - shade 500 */
export const Yellow500 = "#eaaa08" as const;
/** Yellow - shade 600 */
export const Yellow600 = "#ca8504" as const;
/** Yellow - shade 700 */
export const Yellow700 = "#a15c07" as const;
/** Yellow - shade 800 */
export const Yellow800 = "#854a0e" as const;
/** Yellow - shade 900 */
export const Yellow900 = "#713b12" as const;
/** Yellow - shade 950 */
export const Yellow950 = "#542c0d" as const;

// =============================================================================
// Colors Object (for dynamic access)
// =============================================================================

export const colors = {
  BaseWhite: "#ffffff",
  BaseBlack: "#0e0e3f",
  Graylightmode25: "#fdfdfd",
  Graylightmode50: "#fafafa",
  Graylightmode100: "#f5f5f5",
  Graylightmode200: "#e9eaeb",
  Graylightmode300: "#d5d7da",
  Graylightmode400: "#a4a7ae",
  Graylightmode500: "#717680",
  Graylightmode600: "#535862",
  Graylightmode700: "#414651",
  Graylightmode800: "#252b37",
  Graylightmode900: "#181d27",
  Graylightmode950: "#0e0e3f",
  Graydarkmode25: "#fafafa",
  Graydarkmode50: "#f7f7f7",
  Graydarkmode100: "#f0f0f1",
  Graydarkmode200: "#ececed",
  Graydarkmode300: "#cecfd2",
  Graydarkmode400: "#94979c",
  Graydarkmode500: "#85888e",
  Graydarkmode600: "#61656c",
  Graydarkmode700: "#373a41",
  Graydarkmode800: "#22262f",
  Graydarkmode900: "#13161b",
  Graydarkmode950: "#0c0e12",
  Brand25: "#e8f1f9",
  Brand50: "#d0e3f4",
  Brand100: "#b9d5ee",
  Brand200: "#a1c7e9",
  Brand300: "#73acdd",
  Brand400: "#4490d2",
  Brand500: "#1574c7",
  Brand600: "#115d9f",
  Brand700: "#0d4677",
  Brand800: "#082e50",
  Brand900: "#041728",
  Brand950: "#020c14",
  Error25: "#fffbfa",
  Error50: "#fef3f2",
  Error100: "#fee4e2",
  Error200: "#fecdca",
  Error300: "#fda29b",
  Error400: "#f97066",
  Error500: "#f04438",
  Error600: "#d92d20",
  Error700: "#b42318",
  Error800: "#912018",
  Error900: "#7a271a",
  Error950: "#55160c",
  Warning25: "#fffcf5",
  Warning50: "#fffaeb",
  Warning100: "#fef0c7",
  Warning200: "#fedf89",
  Warning300: "#fec84b",
  Warning400: "#fdb022",
  Warning500: "#f79009",
  Warning600: "#dc6803",
  Warning700: "#b54708",
  Warning800: "#93370d",
  Warning900: "#7a2e0e",
  Warning950: "#4e1d09",
  Success25: "#f6fef9",
  Success50: "#ecfdf3",
  Success100: "#dcfae6",
  Success200: "#abefc6",
  Success300: "#75e0a7",
  Success400: "#47cd89",
  Success500: "#17b26a",
  Success600: "#079455",
  Success700: "#067647",
  Success800: "#085d3a",
  Success900: "#074d31",
  Success950: "#053321",
  Grayblue25: "#fcfcfd",
  Grayblue50: "#f8f9fc",
  Grayblue100: "#eaecf5",
  Grayblue200: "#d5d9eb",
  Grayblue300: "#b3b8db",
  Grayblue400: "#717bbc",
  Grayblue500: "#4e5ba6",
  Grayblue600: "#3e4784",
  Grayblue700: "#363f72",
  Grayblue800: "#293056",
  Grayblue900: "#101323",
  Grayblue950: "#0d0f1c",
  Graycool25: "#fcfcfd",
  Graycool50: "#f9f9fb",
  Graycool100: "#eff1f5",
  Graycool200: "#dcdfea",
  Graycool300: "#b9c0d4",
  Graycool400: "#7d89b0",
  Graycool500: "#5d6b98",
  Graycool600: "#4a5578",
  Graycool700: "#404968",
  Graycool800: "#30374f",
  Graycool900: "#111322",
  Graycool950: "#0e101b",
  Graymodern25: "#fcfcfd",
  Graymodern50: "#f8fafc",
  Graymodern100: "#eef2f6",
  Graymodern200: "#e3e8ef",
  Graymodern300: "#cdd5df",
  Graymodern400: "#9aa4b2",
  Graymodern500: "#697586",
  Graymodern600: "#4b5565",
  Graymodern700: "#364152",
  Graymodern800: "#202939",
  Graymodern900: "#121926",
  Graymodern950: "#0d121c",
  Grayneutral25: "#fcfcfd",
  Grayneutral50: "#f9fafb",
  Grayneutral100: "#f3f4f6",
  Grayneutral200: "#e5e7eb",
  Grayneutral300: "#d2d6db",
  Grayneutral400: "#9da4ae",
  Grayneutral500: "#6c737f",
  Grayneutral600: "#4d5761",
  Grayneutral700: "#384250",
  Grayneutral800: "#1f2a37",
  Grayneutral900: "#111927",
  Grayneutral950: "#0d121c",
  Grayiron25: "#fcfcfc",
  Grayiron50: "#fafafa",
  Grayiron100: "#f4f4f5",
  Grayiron200: "#e4e4e7",
  Grayiron300: "#d1d1d6",
  Grayiron400: "#a0a0ab",
  Grayiron500: "#70707b",
  Grayiron600: "#51525c",
  Grayiron700: "#3f3f46",
  Grayiron800: "#26272b",
  Grayiron900: "#1a1a1e",
  Grayiron950: "#131316",
  Graytrue25: "#fcfcfc",
  Graytrue50: "#f7f7f7",
  Graytrue100: "#f5f5f5",
  Graytrue200: "#e5e5e5",
  Graytrue300: "#d6d6d6",
  Graytrue400: "#a3a3a3",
  Graytrue500: "#737373",
  Graytrue600: "#525252",
  Graytrue700: "#424242",
  Graytrue800: "#292929",
  Graytrue900: "#141414",
  Graytrue950: "#0f0f0f",
  Graywarm25: "#fdfdfc",
  Graywarm50: "#fafaf9",
  Graywarm100: "#f5f5f4",
  Graywarm200: "#e7e5e4",
  Graywarm300: "#d7d3d0",
  Graywarm400: "#a9a29d",
  Graywarm500: "#79716b",
  Graywarm600: "#57534e",
  Graywarm700: "#44403c",
  Graywarm800: "#292524",
  Graywarm900: "#1c1917",
  Graywarm950: "#171412",
  Moss25: "#fafdf7",
  Moss50: "#f5fbee",
  Moss100: "#e6f4d7",
  Moss200: "#ceeab0",
  Moss300: "#acdc79",
  Moss400: "#86cb3c",
  Moss500: "#669f2a",
  Moss600: "#4f7a21",
  Moss700: "#3f621a",
  Moss800: "#335015",
  Moss900: "#2b4212",
  Moss950: "#1a280b",
  Greenlight25: "#fafef5",
  Greenlight50: "#f3fee7",
  Greenlight100: "#e3fbcc",
  Greenlight200: "#d0f8ab",
  Greenlight300: "#a6ef67",
  Greenlight400: "#85e13a",
  Greenlight500: "#66c61c",
  Greenlight600: "#4ca30d",
  Greenlight700: "#3b7c0f",
  Greenlight800: "#326212",
  Greenlight900: "#2b5314",
  Greenlight950: "#15290a",
  Green25: "#f6fef9",
  Green50: "#edfcf2",
  Green100: "#d3f8df",
  Green200: "#aaf0c4",
  Green300: "#73e2a3",
  Green400: "#3ccb7f",
  Green500: "#16b364",
  Green600: "#099250",
  Green700: "#087443",
  Green800: "#095c37",
  Green900: "#084c2e",
  Green950: "#052e1c",
  Teal25: "#f6fefc",
  Teal50: "#f0fdf9",
  Teal100: "#ccfbef",
  Teal200: "#99f6e0",
  Teal300: "#5fe9d0",
  Teal400: "#2ed3b7",
  Teal500: "#15b79e",
  Teal600: "#0e9384",
  Teal700: "#107569",
  Teal800: "#125d56",
  Teal900: "#134e48",
  Teal950: "#0a2926",
  Cyan25: "#f5feff",
  Cyan50: "#ecfdff",
  Cyan100: "#cff9fe",
  Cyan200: "#a5f0fc",
  Cyan300: "#67e3f9",
  Cyan400: "#22ccee",
  Cyan500: "#06aed4",
  Cyan600: "#088ab2",
  Cyan700: "#0e7090",
  Cyan800: "#155b75",
  Cyan900: "#164c63",
  Cyan950: "#0d2d3a",
  Bluelight25: "#f6feff",
  Bluelight50: "#f0f9ff",
  Bluelight100: "#e0f2fe",
  Bluelight200: "#b9e6fe",
  Bluelight300: "#7cd4fd",
  Bluelight400: "#36bffa",
  Bluelight500: "#0ba5ec",
  Bluelight600: "#0086c9",
  Bluelight700: "#026aa2",
  Bluelight800: "#065986",
  Bluelight900: "#0b4a6f",
  Bluelight950: "#062c41",
  Blue25: "#e6f2ff",
  Blue50: "#cce5fe",
  Blue100: "#b3d7fe",
  Blue200: "#9acafe",
  Blue300: "#67b0fd",
  Blue400: "#3595fd",
  Blue500: "#027bfc",
  Blue600: "#0262ca",
  Blue700: "#014a97",
  Blue800: "#013165",
  Blue900: "#01254c",
  Blue950: "#001932",
  Bluedark25: "#f5f8ff",
  Bluedark50: "#eff4ff",
  Bluedark100: "#d1e0ff",
  Bluedark200: "#b2ccff",
  Bluedark300: "#84adff",
  Bluedark400: "#528bff",
  Bluedark500: "#2970ff",
  Bluedark600: "#155eef",
  Bluedark700: "#004eeb",
  Bluedark800: "#0040c1",
  Bluedark900: "#00359e",
  Bluedark950: "#002266",
  Indigo25: "#f5f8ff",
  Indigo50: "#eef4ff",
  Indigo100: "#e0eaff",
  Indigo200: "#c7d7fe",
  Indigo300: "#a4bcfd",
  Indigo400: "#8098f9",
  Indigo500: "#6172f3",
  Indigo600: "#444ce7",
  Indigo700: "#3538cd",
  Indigo800: "#2d31a6",
  Indigo900: "#2d3282",
  Indigo950: "#1f235b",
  Violet25: "#fbfaff",
  Violet50: "#f5f3ff",
  Violet100: "#ece9fe",
  Violet200: "#ddd6fe",
  Violet300: "#c3b5fd",
  Violet400: "#a48afb",
  Violet500: "#875bf7",
  Violet600: "#7839ee",
  Violet700: "#6927da",
  Violet800: "#5720b7",
  Violet900: "#491c96",
  Violet950: "#2e125e",
  Purple25: "#fafaff",
  Purple50: "#f4f3ff",
  Purple100: "#ebe9fe",
  Purple200: "#d9d6fe",
  Purple300: "#bdb4fe",
  Purple400: "#9b8afb",
  Purple500: "#7a5af8",
  Purple600: "#6938ef",
  Purple700: "#5925dc",
  Purple800: "#4a1fb8",
  Purple900: "#3e1c96",
  Purple950: "#27115f",
  Fuchsia25: "#fefaff",
  Fuchsia50: "#fdf4ff",
  Fuchsia100: "#fbe8ff",
  Fuchsia200: "#f6d0fe",
  Fuchsia300: "#eeaafd",
  Fuchsia400: "#e478fa",
  Fuchsia500: "#d444f1",
  Fuchsia600: "#ba24d5",
  Fuchsia700: "#9f1ab1",
  Fuchsia800: "#821890",
  Fuchsia900: "#6f1877",
  Fuchsia950: "#47104c",
  Pink25: "#fef6fb",
  Pink50: "#fdf2fa",
  Pink100: "#fce7f6",
  Pink200: "#fcceee",
  Pink300: "#faa7e0",
  Pink400: "#f670c7",
  Pink500: "#ee46bc",
  Pink600: "#dd2590",
  Pink700: "#c11574",
  Pink800: "#9e165f",
  Pink900: "#851651",
  Pink950: "#4e0d30",
  Rose25: "#fff5f6",
  Rose50: "#fff1f3",
  Rose100: "#ffe4e8",
  Rose200: "#fecdd6",
  Rose300: "#fea3b4",
  Rose400: "#fd6f8e",
  Rose500: "#f63d68",
  Rose600: "#e31b54",
  Rose700: "#c01048",
  Rose800: "#a11043",
  Rose900: "#89123e",
  Rose950: "#510b24",
  Orangedark25: "#fff9f5",
  Orangedark50: "#fff4ed",
  Orangedark100: "#ffe6d5",
  Orangedark200: "#ffd6ae",
  Orangedark300: "#ff9c66",
  Orangedark400: "#ff692e",
  Orangedark500: "#ff4405",
  Orangedark600: "#e62e05",
  Orangedark700: "#bc1b06",
  Orangedark800: "#97180c",
  Orangedark900: "#771a0d",
  Orangedark950: "#57130a",
  Orange25: "#fefaf5",
  Orange50: "#fef6ee",
  Orange100: "#fdead7",
  Orange200: "#f9dbaf",
  Orange300: "#f7b27a",
  Orange400: "#f38744",
  Orange500: "#ef6820",
  Orange600: "#e04f16",
  Orange700: "#b93815",
  Orange800: "#932f19",
  Orange900: "#772917",
  Orange950: "#511c10",
  Yellow25: "#fefdf0",
  Yellow50: "#fefbe8",
  Yellow100: "#fef7c3",
  Yellow200: "#feee95",
  Yellow300: "#fde272",
  Yellow400: "#fac515",
  Yellow500: "#eaaa08",
  Yellow600: "#ca8504",
  Yellow700: "#a15c07",
  Yellow800: "#854a0e",
  Yellow900: "#713b12",
  Yellow950: "#542c0d",
} as const;

export type ColorToken = keyof typeof colors;
export type ColorValue = (typeof colors)[ColorToken];
