// This file is auto-generated by scripts/generate-tokens.ts
// Do not edit manually. Update figma/exported-styles.json and run `pnpm generate`

// =============================================================================
// Color Tokens
// =============================================================================

// Base
/** Base - shade White */
export const BaseWhite = "#ffffff" as const;
/** Base - shade Black */
export const BaseBlack = "#0e0e3f" as const;

// Gray (light mode)
/** Gray (light mode) - shade 25 */
export const GrayLightMode25 = "#fdfdfd" as const;
/** Gray (light mode) - shade 50 */
export const GrayLightMode50 = "#fafafa" as const;
/** Gray (light mode) - shade 100 */
export const GrayLightMode100 = "#f5f5f5" as const;
/** Gray (light mode) - shade 200 */
export const GrayLightMode200 = "#e9eaeb" as const;
/** Gray (light mode) - shade 300 */
export const GrayLightMode300 = "#d5d7da" as const;
/** Gray (light mode) - shade 400 */
export const GrayLightMode400 = "#a4a7ae" as const;
/** Gray (light mode) - shade 500 */
export const GrayLightMode500 = "#717680" as const;
/** Gray (light mode) - shade 600 */
export const GrayLightMode600 = "#535862" as const;
/** Gray (light mode) - shade 700 */
export const GrayLightMode700 = "#414651" as const;
/** Gray (light mode) - shade 800 */
export const GrayLightMode800 = "#252b37" as const;
/** Gray (light mode) - shade 900 */
export const GrayLightMode900 = "#181d27" as const;
/** Gray (light mode) - shade 950 */
export const GrayLightMode950 = "#0e0e3f" as const;

// Gray (dark mode)
/** Gray (dark mode) - shade 25 */
export const GrayDarkMode25 = "#fafafa" as const;
/** Gray (dark mode) - shade 50 */
export const GrayDarkMode50 = "#f7f7f7" as const;
/** Gray (dark mode) - shade 100 */
export const GrayDarkMode100 = "#f0f0f1" as const;
/** Gray (dark mode) - shade 200 */
export const GrayDarkMode200 = "#ececed" as const;
/** Gray (dark mode) - shade 300 */
export const GrayDarkMode300 = "#cecfd2" as const;
/** Gray (dark mode) - shade 400 */
export const GrayDarkMode400 = "#94979c" as const;
/** Gray (dark mode) - shade 500 */
export const GrayDarkMode500 = "#85888e" as const;
/** Gray (dark mode) - shade 600 */
export const GrayDarkMode600 = "#61656c" as const;
/** Gray (dark mode) - shade 700 */
export const GrayDarkMode700 = "#373a41" as const;
/** Gray (dark mode) - shade 800 */
export const GrayDarkMode800 = "#22262f" as const;
/** Gray (dark mode) - shade 900 */
export const GrayDarkMode900 = "#13161b" as const;
/** Gray (dark mode) - shade 950 */
export const GrayDarkMode950 = "#0c0e12" as const;

// Brand
/** Brand - shade 25 */
export const Brand25 = "#e8f1f9" as const;
/** Brand - shade 50 */
export const Brand50 = "#d0e3f4" as const;
/** Brand - shade 100 */
export const Brand100 = "#b9d5ee" as const;
/** Brand - shade 200 */
export const Brand200 = "#a1c7e9" as const;
/** Brand - shade 300 */
export const Brand300 = "#73acdd" as const;
/** Brand - shade 400 */
export const Brand400 = "#4490d2" as const;
/** Brand - shade 500 */
export const Brand500 = "#1574c7" as const;
/** Brand - shade 600 */
export const Brand600 = "#115d9f" as const;
/** Brand - shade 700 */
export const Brand700 = "#0d4677" as const;
/** Brand - shade 800 */
export const Brand800 = "#082e50" as const;
/** Brand - shade 900 */
export const Brand900 = "#041728" as const;
/** Brand - shade 950 */
export const Brand950 = "#020c14" as const;

// Error
/** Error - shade 25 */
export const Error25 = "#fffbfa" as const;
/** Error - shade 50 */
export const Error50 = "#fef3f2" as const;
/** Error - shade 100 */
export const Error100 = "#fee4e2" as const;
/** Error - shade 200 */
export const Error200 = "#fecdca" as const;
/** Error - shade 300 */
export const Error300 = "#fda29b" as const;
/** Error - shade 400 */
export const Error400 = "#f97066" as const;
/** Error - shade 500 */
export const Error500 = "#f04438" as const;
/** Error - shade 600 */
export const Error600 = "#d92d20" as const;
/** Error - shade 700 */
export const Error700 = "#b42318" as const;
/** Error - shade 800 */
export const Error800 = "#912018" as const;
/** Error - shade 900 */
export const Error900 = "#7a271a" as const;
/** Error - shade 950 */
export const Error950 = "#55160c" as const;

// Warning
/** Warning - shade 25 */
export const Warning25 = "#fffcf5" as const;
/** Warning - shade 50 */
export const Warning50 = "#fffaeb" as const;
/** Warning - shade 100 */
export const Warning100 = "#fef0c7" as const;
/** Warning - shade 200 */
export const Warning200 = "#fedf89" as const;
/** Warning - shade 300 */
export const Warning300 = "#fec84b" as const;
/** Warning - shade 400 */
export const Warning400 = "#fdb022" as const;
/** Warning - shade 500 */
export const Warning500 = "#f79009" as const;
/** Warning - shade 600 */
export const Warning600 = "#dc6803" as const;
/** Warning - shade 700 */
export const Warning700 = "#b54708" as const;
/** Warning - shade 800 */
export const Warning800 = "#93370d" as const;
/** Warning - shade 900 */
export const Warning900 = "#7a2e0e" as const;
/** Warning - shade 950 */
export const Warning950 = "#4e1d09" as const;

// Success
/** Success - shade 25 */
export const Success25 = "#f6fef9" as const;
/** Success - shade 50 */
export const Success50 = "#ecfdf3" as const;
/** Success - shade 100 */
export const Success100 = "#dcfae6" as const;
/** Success - shade 200 */
export const Success200 = "#abefc6" as const;
/** Success - shade 300 */
export const Success300 = "#75e0a7" as const;
/** Success - shade 400 */
export const Success400 = "#47cd89" as const;
/** Success - shade 500 */
export const Success500 = "#17b26a" as const;
/** Success - shade 600 */
export const Success600 = "#079455" as const;
/** Success - shade 700 */
export const Success700 = "#067647" as const;
/** Success - shade 800 */
export const Success800 = "#085d3a" as const;
/** Success - shade 900 */
export const Success900 = "#074d31" as const;
/** Success - shade 950 */
export const Success950 = "#053321" as const;

// Gray blue
/** Gray blue - shade 25 */
export const GrayBlue25 = "#fcfcfd" as const;
/** Gray blue - shade 50 */
export const GrayBlue50 = "#f8f9fc" as const;
/** Gray blue - shade 100 */
export const GrayBlue100 = "#eaecf5" as const;
/** Gray blue - shade 200 */
export const GrayBlue200 = "#d5d9eb" as const;
/** Gray blue - shade 300 */
export const GrayBlue300 = "#b3b8db" as const;
/** Gray blue - shade 400 */
export const GrayBlue400 = "#717bbc" as const;
/** Gray blue - shade 500 */
export const GrayBlue500 = "#4e5ba6" as const;
/** Gray blue - shade 600 */
export const GrayBlue600 = "#3e4784" as const;
/** Gray blue - shade 700 */
export const GrayBlue700 = "#363f72" as const;
/** Gray blue - shade 800 */
export const GrayBlue800 = "#293056" as const;
/** Gray blue - shade 900 */
export const GrayBlue900 = "#101323" as const;
/** Gray blue - shade 950 */
export const GrayBlue950 = "#0d0f1c" as const;

// Gray cool
/** Gray cool - shade 25 */
export const GrayCool25 = "#fcfcfd" as const;
/** Gray cool - shade 50 */
export const GrayCool50 = "#f9f9fb" as const;
/** Gray cool - shade 100 */
export const GrayCool100 = "#eff1f5" as const;
/** Gray cool - shade 200 */
export const GrayCool200 = "#dcdfea" as const;
/** Gray cool - shade 300 */
export const GrayCool300 = "#b9c0d4" as const;
/** Gray cool - shade 400 */
export const GrayCool400 = "#7d89b0" as const;
/** Gray cool - shade 500 */
export const GrayCool500 = "#5d6b98" as const;
/** Gray cool - shade 600 */
export const GrayCool600 = "#4a5578" as const;
/** Gray cool - shade 700 */
export const GrayCool700 = "#404968" as const;
/** Gray cool - shade 800 */
export const GrayCool800 = "#30374f" as const;
/** Gray cool - shade 900 */
export const GrayCool900 = "#111322" as const;
/** Gray cool - shade 950 */
export const GrayCool950 = "#0e101b" as const;

// Gray modern
/** Gray modern - shade 25 */
export const GrayModern25 = "#fcfcfd" as const;
/** Gray modern - shade 50 */
export const GrayModern50 = "#f8fafc" as const;
/** Gray modern - shade 100 */
export const GrayModern100 = "#eef2f6" as const;
/** Gray modern - shade 200 */
export const GrayModern200 = "#e3e8ef" as const;
/** Gray modern - shade 300 */
export const GrayModern300 = "#cdd5df" as const;
/** Gray modern - shade 400 */
export const GrayModern400 = "#9aa4b2" as const;
/** Gray modern - shade 500 */
export const GrayModern500 = "#697586" as const;
/** Gray modern - shade 600 */
export const GrayModern600 = "#4b5565" as const;
/** Gray modern - shade 700 */
export const GrayModern700 = "#364152" as const;
/** Gray modern - shade 800 */
export const GrayModern800 = "#202939" as const;
/** Gray modern - shade 900 */
export const GrayModern900 = "#121926" as const;
/** Gray modern - shade 950 */
export const GrayModern950 = "#0d121c" as const;

// Gray neutral
/** Gray neutral - shade 25 */
export const GrayNeutral25 = "#fcfcfd" as const;
/** Gray neutral - shade 50 */
export const GrayNeutral50 = "#f9fafb" as const;
/** Gray neutral - shade 100 */
export const GrayNeutral100 = "#f3f4f6" as const;
/** Gray neutral - shade 200 */
export const GrayNeutral200 = "#e5e7eb" as const;
/** Gray neutral - shade 300 */
export const GrayNeutral300 = "#d2d6db" as const;
/** Gray neutral - shade 400 */
export const GrayNeutral400 = "#9da4ae" as const;
/** Gray neutral - shade 500 */
export const GrayNeutral500 = "#6c737f" as const;
/** Gray neutral - shade 600 */
export const GrayNeutral600 = "#4d5761" as const;
/** Gray neutral - shade 700 */
export const GrayNeutral700 = "#384250" as const;
/** Gray neutral - shade 800 */
export const GrayNeutral800 = "#1f2a37" as const;
/** Gray neutral - shade 900 */
export const GrayNeutral900 = "#111927" as const;
/** Gray neutral - shade 950 */
export const GrayNeutral950 = "#0d121c" as const;

// Gray iron
/** Gray iron - shade 25 */
export const GrayIron25 = "#fcfcfc" as const;
/** Gray iron - shade 50 */
export const GrayIron50 = "#fafafa" as const;
/** Gray iron - shade 100 */
export const GrayIron100 = "#f4f4f5" as const;
/** Gray iron - shade 200 */
export const GrayIron200 = "#e4e4e7" as const;
/** Gray iron - shade 300 */
export const GrayIron300 = "#d1d1d6" as const;
/** Gray iron - shade 400 */
export const GrayIron400 = "#a0a0ab" as const;
/** Gray iron - shade 500 */
export const GrayIron500 = "#70707b" as const;
/** Gray iron - shade 600 */
export const GrayIron600 = "#51525c" as const;
/** Gray iron - shade 700 */
export const GrayIron700 = "#3f3f46" as const;
/** Gray iron - shade 800 */
export const GrayIron800 = "#26272b" as const;
/** Gray iron - shade 900 */
export const GrayIron900 = "#1a1a1e" as const;
/** Gray iron - shade 950 */
export const GrayIron950 = "#131316" as const;

// Gray true
/** Gray true - shade 25 */
export const GrayTrue25 = "#fcfcfc" as const;
/** Gray true - shade 50 */
export const GrayTrue50 = "#f7f7f7" as const;
/** Gray true - shade 100 */
export const GrayTrue100 = "#f5f5f5" as const;
/** Gray true - shade 200 */
export const GrayTrue200 = "#e5e5e5" as const;
/** Gray true - shade 300 */
export const GrayTrue300 = "#d6d6d6" as const;
/** Gray true - shade 400 */
export const GrayTrue400 = "#a3a3a3" as const;
/** Gray true - shade 500 */
export const GrayTrue500 = "#737373" as const;
/** Gray true - shade 600 */
export const GrayTrue600 = "#525252" as const;
/** Gray true - shade 700 */
export const GrayTrue700 = "#424242" as const;
/** Gray true - shade 800 */
export const GrayTrue800 = "#292929" as const;
/** Gray true - shade 900 */
export const GrayTrue900 = "#141414" as const;
/** Gray true - shade 950 */
export const GrayTrue950 = "#0f0f0f" as const;

// Gray warm
/** Gray warm - shade 25 */
export const GrayWarm25 = "#fdfdfc" as const;
/** Gray warm - shade 50 */
export const GrayWarm50 = "#fafaf9" as const;
/** Gray warm - shade 100 */
export const GrayWarm100 = "#f5f5f4" as const;
/** Gray warm - shade 200 */
export const GrayWarm200 = "#e7e5e4" as const;
/** Gray warm - shade 300 */
export const GrayWarm300 = "#d7d3d0" as const;
/** Gray warm - shade 400 */
export const GrayWarm400 = "#a9a29d" as const;
/** Gray warm - shade 500 */
export const GrayWarm500 = "#79716b" as const;
/** Gray warm - shade 600 */
export const GrayWarm600 = "#57534e" as const;
/** Gray warm - shade 700 */
export const GrayWarm700 = "#44403c" as const;
/** Gray warm - shade 800 */
export const GrayWarm800 = "#292524" as const;
/** Gray warm - shade 900 */
export const GrayWarm900 = "#1c1917" as const;
/** Gray warm - shade 950 */
export const GrayWarm950 = "#171412" as const;

// Moss
/** Moss - shade 25 */
export const Moss25 = "#fafdf7" as const;
/** Moss - shade 50 */
export const Moss50 = "#f5fbee" as const;
/** Moss - shade 100 */
export const Moss100 = "#e6f4d7" as const;
/** Moss - shade 200 */
export const Moss200 = "#ceeab0" as const;
/** Moss - shade 300 */
export const Moss300 = "#acdc79" as const;
/** Moss - shade 400 */
export const Moss400 = "#86cb3c" as const;
/** Moss - shade 500 */
export const Moss500 = "#669f2a" as const;
/** Moss - shade 600 */
export const Moss600 = "#4f7a21" as const;
/** Moss - shade 700 */
export const Moss700 = "#3f621a" as const;
/** Moss - shade 800 */
export const Moss800 = "#335015" as const;
/** Moss - shade 900 */
export const Moss900 = "#2b4212" as const;
/** Moss - shade 950 */
export const Moss950 = "#1a280b" as const;

// Green light
/** Green light - shade 25 */
export const GreenLight25 = "#fafef5" as const;
/** Green light - shade 50 */
export const GreenLight50 = "#f3fee7" as const;
/** Green light - shade 100 */
export const GreenLight100 = "#e3fbcc" as const;
/** Green light - shade 200 */
export const GreenLight200 = "#d0f8ab" as const;
/** Green light - shade 300 */
export const GreenLight300 = "#a6ef67" as const;
/** Green light - shade 400 */
export const GreenLight400 = "#85e13a" as const;
/** Green light - shade 500 */
export const GreenLight500 = "#66c61c" as const;
/** Green light - shade 600 */
export const GreenLight600 = "#4ca30d" as const;
/** Green light - shade 700 */
export const GreenLight700 = "#3b7c0f" as const;
/** Green light - shade 800 */
export const GreenLight800 = "#326212" as const;
/** Green light - shade 900 */
export const GreenLight900 = "#2b5314" as const;
/** Green light - shade 950 */
export const GreenLight950 = "#15290a" as const;

// Green
/** Green - shade 25 */
export const Green25 = "#f6fef9" as const;
/** Green - shade 50 */
export const Green50 = "#edfcf2" as const;
/** Green - shade 100 */
export const Green100 = "#d3f8df" as const;
/** Green - shade 200 */
export const Green200 = "#aaf0c4" as const;
/** Green - shade 300 */
export const Green300 = "#73e2a3" as const;
/** Green - shade 400 */
export const Green400 = "#3ccb7f" as const;
/** Green - shade 500 */
export const Green500 = "#16b364" as const;
/** Green - shade 600 */
export const Green600 = "#099250" as const;
/** Green - shade 700 */
export const Green700 = "#087443" as const;
/** Green - shade 800 */
export const Green800 = "#095c37" as const;
/** Green - shade 900 */
export const Green900 = "#084c2e" as const;
/** Green - shade 950 */
export const Green950 = "#052e1c" as const;

// Teal
/** Teal - shade 25 */
export const Teal25 = "#f6fefc" as const;
/** Teal - shade 50 */
export const Teal50 = "#f0fdf9" as const;
/** Teal - shade 100 */
export const Teal100 = "#ccfbef" as const;
/** Teal - shade 200 */
export const Teal200 = "#99f6e0" as const;
/** Teal - shade 300 */
export const Teal300 = "#5fe9d0" as const;
/** Teal - shade 400 */
export const Teal400 = "#2ed3b7" as const;
/** Teal - shade 500 */
export const Teal500 = "#15b79e" as const;
/** Teal - shade 600 */
export const Teal600 = "#0e9384" as const;
/** Teal - shade 700 */
export const Teal700 = "#107569" as const;
/** Teal - shade 800 */
export const Teal800 = "#125d56" as const;
/** Teal - shade 900 */
export const Teal900 = "#134e48" as const;
/** Teal - shade 950 */
export const Teal950 = "#0a2926" as const;

// Cyan
/** Cyan - shade 25 */
export const Cyan25 = "#f5feff" as const;
/** Cyan - shade 50 */
export const Cyan50 = "#ecfdff" as const;
/** Cyan - shade 100 */
export const Cyan100 = "#cff9fe" as const;
/** Cyan - shade 200 */
export const Cyan200 = "#a5f0fc" as const;
/** Cyan - shade 300 */
export const Cyan300 = "#67e3f9" as const;
/** Cyan - shade 400 */
export const Cyan400 = "#22ccee" as const;
/** Cyan - shade 500 */
export const Cyan500 = "#06aed4" as const;
/** Cyan - shade 600 */
export const Cyan600 = "#088ab2" as const;
/** Cyan - shade 700 */
export const Cyan700 = "#0e7090" as const;
/** Cyan - shade 800 */
export const Cyan800 = "#155b75" as const;
/** Cyan - shade 900 */
export const Cyan900 = "#164c63" as const;
/** Cyan - shade 950 */
export const Cyan950 = "#0d2d3a" as const;

// Blue light
/** Blue light - shade 25 */
export const BlueLight25 = "#f6feff" as const;
/** Blue light - shade 50 */
export const BlueLight50 = "#f0f9ff" as const;
/** Blue light - shade 100 */
export const BlueLight100 = "#e0f2fe" as const;
/** Blue light - shade 200 */
export const BlueLight200 = "#b9e6fe" as const;
/** Blue light - shade 300 */
export const BlueLight300 = "#7cd4fd" as const;
/** Blue light - shade 400 */
export const BlueLight400 = "#36bffa" as const;
/** Blue light - shade 500 */
export const BlueLight500 = "#0ba5ec" as const;
/** Blue light - shade 600 */
export const BlueLight600 = "#0086c9" as const;
/** Blue light - shade 700 */
export const BlueLight700 = "#026aa2" as const;
/** Blue light - shade 800 */
export const BlueLight800 = "#065986" as const;
/** Blue light - shade 900 */
export const BlueLight900 = "#0b4a6f" as const;
/** Blue light - shade 950 */
export const BlueLight950 = "#062c41" as const;

// Blue
/** Blue - shade 25 */
export const Blue25 = "#e6f2ff" as const;
/** Blue - shade 50 */
export const Blue50 = "#cce5fe" as const;
/** Blue - shade 100 */
export const Blue100 = "#b3d7fe" as const;
/** Blue - shade 200 */
export const Blue200 = "#9acafe" as const;
/** Blue - shade 300 */
export const Blue300 = "#67b0fd" as const;
/** Blue - shade 400 */
export const Blue400 = "#3595fd" as const;
/** Blue - shade 500 */
export const Blue500 = "#027bfc" as const;
/** Blue - shade 600 */
export const Blue600 = "#0262ca" as const;
/** Blue - shade 700 */
export const Blue700 = "#014a97" as const;
/** Blue - shade 800 */
export const Blue800 = "#013165" as const;
/** Blue - shade 900 */
export const Blue900 = "#01254c" as const;
/** Blue - shade 950 */
export const Blue950 = "#001932" as const;

// Blue dark
/** Blue dark - shade 25 */
export const BlueDark25 = "#f5f8ff" as const;
/** Blue dark - shade 50 */
export const BlueDark50 = "#eff4ff" as const;
/** Blue dark - shade 100 */
export const BlueDark100 = "#d1e0ff" as const;
/** Blue dark - shade 200 */
export const BlueDark200 = "#b2ccff" as const;
/** Blue dark - shade 300 */
export const BlueDark300 = "#84adff" as const;
/** Blue dark - shade 400 */
export const BlueDark400 = "#528bff" as const;
/** Blue dark - shade 500 */
export const BlueDark500 = "#2970ff" as const;
/** Blue dark - shade 600 */
export const BlueDark600 = "#155eef" as const;
/** Blue dark - shade 700 */
export const BlueDark700 = "#004eeb" as const;
/** Blue dark - shade 800 */
export const BlueDark800 = "#0040c1" as const;
/** Blue dark - shade 900 */
export const BlueDark900 = "#00359e" as const;
/** Blue dark - shade 950 */
export const BlueDark950 = "#002266" as const;

// Indigo
/** Indigo - shade 25 */
export const Indigo25 = "#f5f8ff" as const;
/** Indigo - shade 50 */
export const Indigo50 = "#eef4ff" as const;
/** Indigo - shade 100 */
export const Indigo100 = "#e0eaff" as const;
/** Indigo - shade 200 */
export const Indigo200 = "#c7d7fe" as const;
/** Indigo - shade 300 */
export const Indigo300 = "#a4bcfd" as const;
/** Indigo - shade 400 */
export const Indigo400 = "#8098f9" as const;
/** Indigo - shade 500 */
export const Indigo500 = "#6172f3" as const;
/** Indigo - shade 600 */
export const Indigo600 = "#444ce7" as const;
/** Indigo - shade 700 */
export const Indigo700 = "#3538cd" as const;
/** Indigo - shade 800 */
export const Indigo800 = "#2d31a6" as const;
/** Indigo - shade 900 */
export const Indigo900 = "#2d3282" as const;
/** Indigo - shade 950 */
export const Indigo950 = "#1f235b" as const;

// Violet
/** Violet - shade 25 */
export const Violet25 = "#fbfaff" as const;
/** Violet - shade 50 */
export const Violet50 = "#f5f3ff" as const;
/** Violet - shade 100 */
export const Violet100 = "#ece9fe" as const;
/** Violet - shade 200 */
export const Violet200 = "#ddd6fe" as const;
/** Violet - shade 300 */
export const Violet300 = "#c3b5fd" as const;
/** Violet - shade 400 */
export const Violet400 = "#a48afb" as const;
/** Violet - shade 500 */
export const Violet500 = "#875bf7" as const;
/** Violet - shade 600 */
export const Violet600 = "#7839ee" as const;
/** Violet - shade 700 */
export const Violet700 = "#6927da" as const;
/** Violet - shade 800 */
export const Violet800 = "#5720b7" as const;
/** Violet - shade 900 */
export const Violet900 = "#491c96" as const;
/** Violet - shade 950 */
export const Violet950 = "#2e125e" as const;

// Purple
/** Purple - shade 25 */
export const Purple25 = "#fafaff" as const;
/** Purple - shade 50 */
export const Purple50 = "#f4f3ff" as const;
/** Purple - shade 100 */
export const Purple100 = "#ebe9fe" as const;
/** Purple - shade 200 */
export const Purple200 = "#d9d6fe" as const;
/** Purple - shade 300 */
export const Purple300 = "#bdb4fe" as const;
/** Purple - shade 400 */
export const Purple400 = "#9b8afb" as const;
/** Purple - shade 500 */
export const Purple500 = "#7a5af8" as const;
/** Purple - shade 600 */
export const Purple600 = "#6938ef" as const;
/** Purple - shade 700 */
export const Purple700 = "#5925dc" as const;
/** Purple - shade 800 */
export const Purple800 = "#4a1fb8" as const;
/** Purple - shade 900 */
export const Purple900 = "#3e1c96" as const;
/** Purple - shade 950 */
export const Purple950 = "#27115f" as const;

// Fuchsia
/** Fuchsia - shade 25 */
export const Fuchsia25 = "#fefaff" as const;
/** Fuchsia - shade 50 */
export const Fuchsia50 = "#fdf4ff" as const;
/** Fuchsia - shade 100 */
export const Fuchsia100 = "#fbe8ff" as const;
/** Fuchsia - shade 200 */
export const Fuchsia200 = "#f6d0fe" as const;
/** Fuchsia - shade 300 */
export const Fuchsia300 = "#eeaafd" as const;
/** Fuchsia - shade 400 */
export const Fuchsia400 = "#e478fa" as const;
/** Fuchsia - shade 500 */
export const Fuchsia500 = "#d444f1" as const;
/** Fuchsia - shade 600 */
export const Fuchsia600 = "#ba24d5" as const;
/** Fuchsia - shade 700 */
export const Fuchsia700 = "#9f1ab1" as const;
/** Fuchsia - shade 800 */
export const Fuchsia800 = "#821890" as const;
/** Fuchsia - shade 900 */
export const Fuchsia900 = "#6f1877" as const;
/** Fuchsia - shade 950 */
export const Fuchsia950 = "#47104c" as const;

// Pink
/** Pink - shade 25 */
export const Pink25 = "#fef6fb" as const;
/** Pink - shade 50 */
export const Pink50 = "#fdf2fa" as const;
/** Pink - shade 100 */
export const Pink100 = "#fce7f6" as const;
/** Pink - shade 200 */
export const Pink200 = "#fcceee" as const;
/** Pink - shade 300 */
export const Pink300 = "#faa7e0" as const;
/** Pink - shade 400 */
export const Pink400 = "#f670c7" as const;
/** Pink - shade 500 */
export const Pink500 = "#ee46bc" as const;
/** Pink - shade 600 */
export const Pink600 = "#dd2590" as const;
/** Pink - shade 700 */
export const Pink700 = "#c11574" as const;
/** Pink - shade 800 */
export const Pink800 = "#9e165f" as const;
/** Pink - shade 900 */
export const Pink900 = "#851651" as const;
/** Pink - shade 950 */
export const Pink950 = "#4e0d30" as const;

// Rose
/** Rose - shade 25 */
export const Rose25 = "#fff5f6" as const;
/** Rose - shade 50 */
export const Rose50 = "#fff1f3" as const;
/** Rose - shade 100 */
export const Rose100 = "#ffe4e8" as const;
/** Rose - shade 200 */
export const Rose200 = "#fecdd6" as const;
/** Rose - shade 300 */
export const Rose300 = "#fea3b4" as const;
/** Rose - shade 400 */
export const Rose400 = "#fd6f8e" as const;
/** Rose - shade 500 */
export const Rose500 = "#f63d68" as const;
/** Rose - shade 600 */
export const Rose600 = "#e31b54" as const;
/** Rose - shade 700 */
export const Rose700 = "#c01048" as const;
/** Rose - shade 800 */
export const Rose800 = "#a11043" as const;
/** Rose - shade 900 */
export const Rose900 = "#89123e" as const;
/** Rose - shade 950 */
export const Rose950 = "#510b24" as const;

// Orange dark
/** Orange dark - shade 25 */
export const OrangeDark25 = "#fff9f5" as const;
/** Orange dark - shade 50 */
export const OrangeDark50 = "#fff4ed" as const;
/** Orange dark - shade 100 */
export const OrangeDark100 = "#ffe6d5" as const;
/** Orange dark - shade 200 */
export const OrangeDark200 = "#ffd6ae" as const;
/** Orange dark - shade 300 */
export const OrangeDark300 = "#ff9c66" as const;
/** Orange dark - shade 400 */
export const OrangeDark400 = "#ff692e" as const;
/** Orange dark - shade 500 */
export const OrangeDark500 = "#ff4405" as const;
/** Orange dark - shade 600 */
export const OrangeDark600 = "#e62e05" as const;
/** Orange dark - shade 700 */
export const OrangeDark700 = "#bc1b06" as const;
/** Orange dark - shade 800 */
export const OrangeDark800 = "#97180c" as const;
/** Orange dark - shade 900 */
export const OrangeDark900 = "#771a0d" as const;
/** Orange dark - shade 950 */
export const OrangeDark950 = "#57130a" as const;

// Orange
/** Orange - shade 25 */
export const Orange25 = "#fefaf5" as const;
/** Orange - shade 50 */
export const Orange50 = "#fef6ee" as const;
/** Orange - shade 100 */
export const Orange100 = "#fdead7" as const;
/** Orange - shade 200 */
export const Orange200 = "#f9dbaf" as const;
/** Orange - shade 300 */
export const Orange300 = "#f7b27a" as const;
/** Orange - shade 400 */
export const Orange400 = "#f38744" as const;
/** Orange - shade 500 */
export const Orange500 = "#ef6820" as const;
/** Orange - shade 600 */
export const Orange600 = "#e04f16" as const;
/** Orange - shade 700 */
export const Orange700 = "#b93815" as const;
/** Orange - shade 800 */
export const Orange800 = "#932f19" as const;
/** Orange - shade 900 */
export const Orange900 = "#772917" as const;
/** Orange - shade 950 */
export const Orange950 = "#511c10" as const;

// Yellow
/** Yellow - shade 25 */
export const Yellow25 = "#fefdf0" as const;
/** Yellow - shade 50 */
export const Yellow50 = "#fefbe8" as const;
/** Yellow - shade 100 */
export const Yellow100 = "#fef7c3" as const;
/** Yellow - shade 200 */
export const Yellow200 = "#feee95" as const;
/** Yellow - shade 300 */
export const Yellow300 = "#fde272" as const;
/** Yellow - shade 400 */
export const Yellow400 = "#fac515" as const;
/** Yellow - shade 500 */
export const Yellow500 = "#eaaa08" as const;
/** Yellow - shade 600 */
export const Yellow600 = "#ca8504" as const;
/** Yellow - shade 700 */
export const Yellow700 = "#a15c07" as const;
/** Yellow - shade 800 */
export const Yellow800 = "#854a0e" as const;
/** Yellow - shade 900 */
export const Yellow900 = "#713b12" as const;
/** Yellow - shade 950 */
export const Yellow950 = "#542c0d" as const;

// =============================================================================
// Colors Object (for dynamic access)
// =============================================================================

export const colors = {
  BaseWhite: "#ffffff",
  BaseBlack: "#0e0e3f",
  GrayLightMode25: "#fdfdfd",
  GrayLightMode50: "#fafafa",
  GrayLightMode100: "#f5f5f5",
  GrayLightMode200: "#e9eaeb",
  GrayLightMode300: "#d5d7da",
  GrayLightMode400: "#a4a7ae",
  GrayLightMode500: "#717680",
  GrayLightMode600: "#535862",
  GrayLightMode700: "#414651",
  GrayLightMode800: "#252b37",
  GrayLightMode900: "#181d27",
  GrayLightMode950: "#0e0e3f",
  GrayDarkMode25: "#fafafa",
  GrayDarkMode50: "#f7f7f7",
  GrayDarkMode100: "#f0f0f1",
  GrayDarkMode200: "#ececed",
  GrayDarkMode300: "#cecfd2",
  GrayDarkMode400: "#94979c",
  GrayDarkMode500: "#85888e",
  GrayDarkMode600: "#61656c",
  GrayDarkMode700: "#373a41",
  GrayDarkMode800: "#22262f",
  GrayDarkMode900: "#13161b",
  GrayDarkMode950: "#0c0e12",
  Brand25: "#e8f1f9",
  Brand50: "#d0e3f4",
  Brand100: "#b9d5ee",
  Brand200: "#a1c7e9",
  Brand300: "#73acdd",
  Brand400: "#4490d2",
  Brand500: "#1574c7",
  Brand600: "#115d9f",
  Brand700: "#0d4677",
  Brand800: "#082e50",
  Brand900: "#041728",
  Brand950: "#020c14",
  Error25: "#fffbfa",
  Error50: "#fef3f2",
  Error100: "#fee4e2",
  Error200: "#fecdca",
  Error300: "#fda29b",
  Error400: "#f97066",
  Error500: "#f04438",
  Error600: "#d92d20",
  Error700: "#b42318",
  Error800: "#912018",
  Error900: "#7a271a",
  Error950: "#55160c",
  Warning25: "#fffcf5",
  Warning50: "#fffaeb",
  Warning100: "#fef0c7",
  Warning200: "#fedf89",
  Warning300: "#fec84b",
  Warning400: "#fdb022",
  Warning500: "#f79009",
  Warning600: "#dc6803",
  Warning700: "#b54708",
  Warning800: "#93370d",
  Warning900: "#7a2e0e",
  Warning950: "#4e1d09",
  Success25: "#f6fef9",
  Success50: "#ecfdf3",
  Success100: "#dcfae6",
  Success200: "#abefc6",
  Success300: "#75e0a7",
  Success400: "#47cd89",
  Success500: "#17b26a",
  Success600: "#079455",
  Success700: "#067647",
  Success800: "#085d3a",
  Success900: "#074d31",
  Success950: "#053321",
} as const;

export type ColorToken = keyof typeof colors;
export type ColorValue = (typeof colors)[ColorToken];
